sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - echo "deb http://httpredir.debian.org/debian jessie main contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.9 -y

install: true

before_script:
 mkdir build
 cd build
 cmake .. -DCMAKE_BUILD_TYPE=Release
 gcc --version

script:
 make

notifications:
  email:
    recipients:
      - sendspam@mail2nowhere.com
    on_success: always
    on_failure: always
