language: cpp

matrix:
 include:
  -env: CLANG_VERSION=3.5
   os: linux
   addons: &clang35
     apt:
      packages:
            - clang-3.5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

  - env: GCC_VERSION=4.8 
    os: linux
    addons: &gcc48
      apt:
          packages:
            - g++-4.8
          sources:
            - ubuntu-toolchain-r-test


before_install:
  - export CHECKOUT_PATH=`pwd`;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [ "$CLANG_VERSION" == "3.4" ]; then export CXX="/usr/local/clang-3.4/bin/clang++" CC="/usr/local/clang-3.4/bin/clang"; fi
  - which $CXX
  - which $CC
#  - if [ -n "$CLANG_VERSION" ]; then CXX=$CXX CC=$CC; fi

script:
  $CXX --version