sudo: false
language: cpp
compiler:
  - gcc

install: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9

before_script:
 mkdir build
 cd build
 cmake .. -DCMAKE_BUILD_TYPE=Release

script:
 make

notifications:
  email: 
    - sendspam@mail2nowhere.com
    on_success: always
    on_failure: always
