sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.9 -y --force-yes
  - export CXX="gcc-4.9"

install: true

before_script:
 mkdir build
 cd build
 cmake .. -DCMAKE_BUILD_TYPE=Release
 gcc --version

script:
 make

notifications:
  email:
    recipients:
      - sendspam@mail2nowhere.com
    on_success: always
    on_failure: always
