sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.9 g++-4.9 -y --force-yes
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"

install: true

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - gcc --version

script:
  - make

after_success:
  - echo "test" 
    | checkinstall -D --install="no" --nodoc --pkgname "apps" --pkgversion "1.0" 
                   --pkgarch "amd64" --pkgrelease "1" --maintainer "Travis" 
                   --pkgsource "https://github.com/anton-seliverstov/Apps.git" 
                   --pkggroup "misc" --pkglicense "GNU General Public License, Version 3" 

notifications:
  email:
    recipients:
      - sendspam@mail2nowhere.com
    on_success: always
    on_failure: always
